# Generated by Django 6.0.6 on 2026-06-11 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.PositiveIntegerField()),
                ('resting_hr', models.PositiveIntegerField()),
                ('max_hr', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('target_distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_date', models.DateField()),
                ('target_pace_min_per_km', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='diary.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('avg_heart_rate', models.PositiveIntegerField()),
                ('workout_type', models.CharField(choices=[('easy', 'Лёгкая'), ('tempo', 'Темповая'), ('interval', 'Интервальная'), ('long', 'Длинная'), ('recovery', 'Восстановительная')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='diary.athlete')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='diary.traininggoal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
